language: php
dist: bionic
sudo: false

php:
  - 7.3
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    - RELEASE=dev COMPOSER_CHANNEL=stable
    - RELEASE=stable COMPOSER_CHANNEL=snapshot

before_install:
  # https://www.drupal.org/project/drupal/issues/3107155
  - sudo echo "deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y install sqlite3/focal
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose install

script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core-recommended:9.0.x-dev; composer --verbose require --no-update --dev drupal/core-dev:9.0.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - ./vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  # Run a single unit test to verfiy the testing setup.
  - ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php
  - ./vendor/bin/drush
